# Generated by Django 4.1.2 on 2022-11-04 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('todo_desc', models.CharField(max_length=128)),
                ('todo_complete', models.BooleanField()),
                ('todo_delete', models.BooleanField()),
            ],
        ),
    ]
