# Generated by Django 4.1.2 on 2022-11-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_order',
            field=models.IntegerField(default=1),
        ),
    ]
