# Generated by Django 4.1.2 on 2022-11-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_todo_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_order',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_current',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_next',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_previous',
            field=models.IntegerField(default=-1),
        ),
    ]
