# Generated by Django 4.1.2 on 2022-11-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_todo_current_alter_todo_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_next',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_previous',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_index_number',
            field=models.IntegerField(default=-1),
        ),
    ]
